---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: consent
  jobs:
  - name: npm
    type: builder
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      export NVM_DIR=/home/pipeline/nvm
      export NODE_VERSION=10.16.0
      export NVM_VERSION=0.29.0

      cd angular-src

      npm config delete prefix \
        && curl https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | sh \
        && . $NVM_DIR/nvm.sh \
        && nvm install $NODE_VERSION \
        && nvm alias default $NODE_VERSION \
        && nvm use default \
        && node -v \
        && npm -v

      npm install -g @angular/cli
      npm install

      ng build --prod

      cd ..
      npm install
